pipeline:
  setting: 'research' #options: 'service', 'research', or 'all'. Select 'service' with minimal rules for providing services. Select 'research' with rules for research purposes, select them in Snakefile under rule research. For all rules select 'all'.
  THREADS: 4
  suppressMessages: TRUE #options TRUE or FALSE, TRUE for suppressed library messages and warnings of R-packages

path:
  dir_fastq: "/net/beegfs/cfg/tgac/yokim/FB09229586_9/fastq/sorted/" # directory that contains the fastq-files 
  dir_out: "/net/beegfs/cfg/tgac/yokim/FB09229586_9/"  # directory where the output should be created, all other directories below are branches of this directory
  dir_qc: "qc/"
  dir_bam: "bam/"
  dir_stats: "stats/"
  dir_log: "log/"

summary:
  profiletypes: ["corrected", "segmented", "called"] # if dewaving is skipped, delete dewaved


bwa:
  REF: "/net/nfs/PAT/archive/Resource/fasta/hg19.fa"
  max_edit_distance: 2  #n
  read_trimming_param: 40 #q

QDNAseq:
  BINSIZES: ["15", "30",  "100", "500", "1000"]   #required binsizes comma seperated  1 5 10 15 30 100 1000
  genome: hg19
  chrom_filter: ["Y", "X"] # comma separated quoted to specify which chromosomes to filter out. "X","Y"
  dewave: False #dewaving is an optional setting, if True samples will be dewaved before segmentation, if False dewaving will be skipped.
  dewave_dir: scripts/QDNAseq.dev-dewave/R
  # dewave_data: scripts/QDNAseq.dev-dewave/data/NormalCalibrationSet_{binSize}kb.rda
  dewave_data: data/NormalCalibrationSet_{binSize}kb.rda
  minimal_used_reads: 100000
  minimum_cellularity: 0.2  # minimum cellularity used for calling, a to low cellularity cause over calling.

BED:
  max_focal_size_bed: 5 #in creations bedfiles

CGHregions:
  averror: 0.01  #0.0075	 # default = 0.01
  min_freq_focal: 25
  max_focal_size_mb: 15
  cytobands: /net/beegfs/cfg/tgac/Resource/fasta/cytoBand.txt.gz

ACE:
  ploidies: [2] # [2,4]   #required ploidies comma seperated
  main_ploidy: 2   # only the main ploidy fitpicker file will be used for calling based on cellularity
  imagetype: png      #options are png, pdf
  method: RMSE        #'RMSE' root mean squared error, 'MAE' weighs every error equally, 'SMRE' punish more the long segments that are a little bit off compared to the short segments that are way off
  penalty: 0.5          #sets a penalty for the error calculated at lower cellularity
  cap: 12             # which copy numbers are capped (highest value)
  trncname: FALSE     #Samplenames are truncated after _
  printsummaries: FALSE  #options: TRUE, FALSE or 2, TRUE is only possible for less than ~ 50 samples. 2 means that only the errorplots are in a summary file.
  ACEBINSIZES: [100] #required binsizes comma seperated 15 30 100 1000, be careful not to ask for binsizes not created by QDNAseq. Smaller binsizes are computationally harder.

CGHtest:
    clinicaldataPath: 'data/clinical.xlsx'  # string, input path to clincal data set, assumed excel sheet
    columnSampleNames: 1    # integer, what is index of the column containing the sample names, in the clinical data
    ClassSamples: ['short', 'long'] # list containing two strings,  what are the classes that the samples are identified with
    columnClassSamples: 3   # integer, what is index of the column containing the sample classes, in the clinical data 
