channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python=3.9
  - bwa
  - samtools
  - snakemake>5.31
  - pyyaml
  - picard==2.20.8
  - fastqc
  - perl-bioperl
  - perl-dbd-mysql
  - bioconductor-qdnaseq.hg19
  - bioconductor-biobase
  - bioconductor-cghcall
  - bioconductor-cghregions
  - bioconductor-limma
  - bioconductor-impute
  - r-matrixstats
  - r-r.cache
  - r-denstrip
  - r-flexmix
  - r-gtools
  - r-mass
  - r-devtools==2.4.3
  - r-ggplot2
  - r-survival
  - r-readxl
